title: Software
nav:
  - material-maker.md
  - ucupaint.md
  - substance-painter.md
  - mari.md
  - photoshop.md
  - krita.md
  - marmoset-toolbag.md
  - marvelous-designer.md
  - poly-haven.md
  - ambientcg.md
