title: Paths
nav:
  - Blender foundations: blender-foundations.md
  - 3D model artist: 3d-model-artist.md
  - Texture artist: texture-artist.md
  - Rigging & animation: rigging-animation.md
  - Second Life creator: second-life-creator.md
  - Breedables engineer: breedables-engineer.md
