title: 3D Modeling
nav:
  - Overview: index.md
  - Blender: blender
  - Workflows:
      - mesh-modeling.md
      - sculpting.md
      - retopology.md
      - uv-mapping.md
  - Other software: software
  - Projects: projects
